---
name: Main

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Lint
        uses: reviewdog/action-golangci-lint@v1.17.0
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml"

      - name: Setup env
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
          mkdir -p "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel"
          ln -sf "$GITHUB_WORKSPACE/" "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/go-netbox"
        shell: bash

      - name: Swagger and patchs
        run: |
          NETBOX_MAJOR_VERSION=$(cat netbox_major_version)
          echo "NETBOX_MAJOR_VERSION=${NETBOX_MAJOR_VERSION}"
          LAST_NETBOX_VERSION="$(./utils/netbox_get_last_version ${NETBOX_MAJOR_VERSION})"
          echo "LAST_NETBOX_VERSION=${LAST_NETBOX_VERSION}"
          export VERSION=${LAST_NETBOX_VERSION}
          git clone https://github.com/netbox-community/netbox-docker.git
          cd netbox-docker
          mv docker-compose.override.yml.example docker-compose.override.yml
          docker-compose up -d
          cd ..
          while ! curl -s http://127.0.0.1:8000/api/swagger.json -o swagger.json 2> /dev/null; do sleep 1; done
          curl -sL https://github.com/go-swagger/go-swagger/releases/download/v0.27.0/swagger_linux_amd64 -o swagger
          chmod 755 swagger
          rm -rf netbox && mkdir netbox && touch netbox/.gitkeep
          ./swagger generate client -f swagger.json -A go-netbox -t "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/go-netbox/netbox" --copyright-file="$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/go-netbox/LICENSE"
          find patchs -type f -name "*.patch" | xargs patch -p0
        shell: bash

      - name: Commit library
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: 'netbox'
          author_name: smutel
          default_author: github_actor
          message: 'ci: Autogeneration of go-netbox library'
          pull_strategy: '--rebase'
